#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Mon Jan 30 10:17:54 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class _284776066__815403082_MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: _284776066__815403082_MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.mainFrame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "New", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_ANY, "exit", "", wx.ITEM_NORMAL)
        self.mainFrame_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.mainFrame_menubar)
        # Menu Bar end
        self.mainFrame_statusbar = self.CreateStatusBar(2)
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.Tuning_Parameters = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.Proportional_Gain = wx.StaticText(self.Tuning_Parameters, wx.ID_ANY, "label_1")
        self.Integral_Gain = wx.StaticText(self.Tuning_Parameters, wx.ID_ANY, "label_1")
        self.Camera = wx.Panel(self.notebook_1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: _284776066__815403082_MyFrame.__set_properties
        self.SetTitle("Frame with Notebook")
        self.mainFrame_statusbar.SetStatusWidths([-1, -1])

        # statusbar fields
        mainFrame_statusbar_fields = ["Test_Status", "PID Tuner"]
        for i in range(len(mainFrame_statusbar_fields)):
            self.mainFrame_statusbar.SetStatusText(mainFrame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: _284776066__815403082_MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.Tuning_Parameters, wx.ID_ANY, "PID Inputs"), wx.VERTICAL)
        sizer_2.Add(self.Proportional_Gain, 0, 0, 0)
        sizer_2.Add(self.Integral_Gain, 0, wx.ALL, 0)
        self.Tuning_Parameters.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.Tuning_Parameters, "Tuning_Parameters")
        self.notebook_1.AddPage(self.Camera, "Camera")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class _284776066__815403082_MyFrame
if __name__ == "__main__":
    PID_Tuner = wx.PySimpleApp()
    mainFrame = _284776066__815403082_MyFrame(None, wx.ID_ANY, "")
    PID_Tuner.SetTopWindow(mainFrame)
    mainFrame.Show()
    PID_Tuner.MainLoop()
